version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "master"
    allow:
      - dependency-type: "direct"
    cooldown:
      default-days: 14
