mainGuildId = 370708369951948800
mailGuildId = 370708369951948800
logChannelId = 778263487482691665

pinThreadHeader = on
allowMove = on
typingProxy = on
# forceAnon = on
# attachmentStorage = local
status = DM ME FOR HELP
categoryAutomation.newThread = 719883529470738523
inboxServerPermission[] = kickMembers
inboxServerPermission[] = 260600155630338048
prefix = ?
mentionRole = 736365465353453663
closeMessage = "This thread has now been closed. Please don't send a reply unless you wish to open a new thread."
responseMessage = Your message has been attached to Hawky and is on its way! Our mod team will reply to you here as soon as possible. In the meantime, if you are looking for a reason behind a punishment, be sure to re-read the message that Zeppelin sent you!
snippetPrefix = ??
snippetPrefixAnon = ???
updateNotifications = off
rolesInThreadHeader = on
mentionUserInThreadHeader = on
ignoreAccidentalThreads = on
# useNicknames = on
autoAlert = on 
autoAlertDelay = 1m
reactOnSeen = on
updateMessagesLive = on

allowedCategories[] = 719883529470738523 ; Lake Laogai
allowedCategories[] = 828540781291241492 ; The Garden Gate
allowedCategories[] = 1039274712905298062 ; Community
communityThreadCategoryId = 1039274712905298062
adminChannelId = 370708369951948802
adminCategoryId = 828540781291241492
# adminMentionRole = 871374249808527380 ; + role
# adminHerePing = on
# adminEveryonePing = on
inboxAdminRoleIDs[] = 871374249808527380
inboxAdminRoleIDs[] = 1163857153644306472 ; Advisor role

blockMessage = You have been blocked from this service permanently. If you wish to appeal this block, please reach out to a White Lotus member. In all instances, please refrain from continuing any related behaviour as this may result in further removal/lack of appeal. 
timedBlockMessage = You have been temporarily blocked from our modmail service. You will be notified when this block expires.
blockedReply = You are currently blocked from this service. Please contact a White Lotus member to appeal this. Any harassment/continued unwanted behaviour in DMs may lead to further punishment. 
unblockMessage = The earth king has granted you another audience. You are unblocked and are free to use this service to contact staff.

; plugins[] = npm:MMPlugins/LogSearch
; plugins[] = npm:funkyhippo/modmailbot-formatter
; plugins[] = npm:MMPlugins/HexedHelp

plugins[] = ../Plugins/LogSearch/logsearch.js
plugins[] = ../Plugins/modmailbot-formatter/index.js
plugins[] = ../Plugins/HexedHelp/help.js
plugins[] = ../Plugins/Ping/ping.js
plugins[] = ../Plugins/MMEmergencyLink/emergencyLink.js

extraIntents[] = guildMessageReactions

port = 8080
url = https://hawky.atla.sh
