version: "3.7"

services:
  modmailbot:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - db-data:/usr/modmailbot/db
      - logs:/usr/modmailbot/logs
      - attachments:/usr/modmailbot/attachments
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - ${PORT:-8890}:${PORT:-8890}

volumes:
  db-data:
    name: "db-data"
  logs:
    name: "logs"
  attachments:
    name: "attachments"
